=== deividkamenov/Wineries-in-Bulgaria-XML/XML/catalogueDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalog (region+)>
<!ELEMENT region (name, winery+)>
<!ATTLIST region id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT winery (name, location, year, grapes, description, image, wine+)>
<!ATTLIST winery id ID #REQUIRED
                 region IDREF #REQUIRED>
<!ELEMENT location (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT grapes (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image EMPTY>
<!ATTLIST image src ENTITY #REQUIRED
                style CDATA #REQUIRED>
<!ELEMENT wine (name, year, grapes, description, image)>
<!ATTLIST wine id ID #REQUIRED
               winery IDREF #REQUIRED>
<!NOTATION JPG SYSTEM "image/jpeg">
<!ENTITY winery_image1 SYSTEM "./winery_image1.jpg" NDATA JPG>
<!ENTITY winery_image2 SYSTEM "./winery_image2.jpg" NDATA JPG>
<!ENTITY winery_image3 SYSTEM "./winery_image3.jpg" NDATA JPG>
<!ENTITY winery_image4 SYSTEM "./winery_image4.jpg" NDATA JPG> 
<!ENTITY winery_image5 SYSTEM "./winery_image5.jpg" NDATA JPG>
<!ENTITY winery_image6 SYSTEM "./winery_image6.jpg" NDATA JPG>
<!ENTITY winery_image7 SYSTEM "./winery_image7.jpg" NDATA JPG>
<!ENTITY winery_image8 SYSTEM "./winery_image8.jpg" NDATA JPG> 
<!ENTITY wine_image1 SYSTEM "./wine_image1.jpg" NDATA JPG>
<!ENTITY wine_image2 SYSTEM "./wine_image2.jpg" NDATA JPG>
<!ENTITY wine_image3 SYSTEM "./wine_image3.jpg" NDATA JPG> 
<!ENTITY wine_image4 SYSTEM "./wine_image4.jpg" NDATA JPG>
<!ENTITY wine_image5 SYSTEM "./wine_image5.jpg" NDATA JPG>
<!ENTITY wine_image6 SYSTEM "./wine_image6.jpg" NDATA JPG>
<!ENTITY wine_image7 SYSTEM "./wine_image7.jpg" NDATA JPG> 
<!ENTITY wine_image8 SYSTEM "./wine_image8.jpg" NDATA JPG>
<!ENTITY wine_image9 SYSTEM "./wine_image9.jpg" NDATA JPG> 
<!ENTITY wine_image10 SYSTEM "./wine_image10.jpg" NDATA JPG> 
<!ENTITY wine_image11 SYSTEM "./wine_image11.jpg" NDATA JPG>
<!ENTITY wine_image12 SYSTEM "./wine_image12.jpg" NDATA JPG>
<!ENTITY wine_image13 SYSTEM "./wine_image13.jpg" NDATA JPG>
<!ENTITY wine_image14 SYSTEM "./wine_image14.jpg" NDATA JPG> 
<!ENTITY wine_image15 SYSTEM "./wine_image15.jpg" NDATA JPG>
<!ENTITY wine_image16 SYSTEM "./wine_image16.jpg" NDATA JPG>

=== deividkamenov/Wineries-in-Bulgaria-XML/XML/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalogueXSLTToPDF.xsl"?>
<!DOCTYPE catalog SYSTEM "catalogueDTD.dtd">
<catalog>
    <region id="region1">
        <name>Розова долина</name>
        <winery id="winery1" region="region1">
            <name>Шато копса</name>
            <location>с. Мосоковец</location>
            <year>1998</year>
            <grapes>шардоне, мускат, совиньон блан, мерло и каберне совиньон, червен мискет</grapes>
            <description>Една от най-привлекателните дестинации за винен туризъм в сърцето на Розовата долина е Шато
                Копса. Постройката е умален средновековен замък, в който е вкопана избата. Енолози са Мадлена и Ангел
                Кузманови. Вината са в елегантна стилистика от шардоне, мускат, совиньон блан, мерло и каберне совиньон.
                Емблема на избата е финото бяло вино от типичния за Розовата долина сорт червен мискет, което се
                отличава с деликатен аромат, лека свежест и пи- кантна горчивина.
            </description>
            <image src="winery_image1" style="width:800px;height:640px"/>
            <wine id="wine1" winery="winery1">
                <name>Chateu Copsa AXL Misket 2021</name>
                <year>2021</year>
                <grapes>Карловски мискет</grapes>
                <description>Моног блед, прозрачен цвят с гнланц. Ароматът е въздържан, долавят се нотки на барут,
                    сушени билки и кайсия с костилка.
                </description>
                <image src="wine_image1" style="width:800px;height:640px"/>
            </wine>
            <wine id="wine2" winery="winery1">
                <name>Chateau Copsa 8TH Merlot and Cabernet Sauvignon 2015</name>
                <year>2015</year>
                <grapes>Каберне совиньон</grapes>
                <description>Красив, запазен рубинен цвят. Ефектен, елегантен нос с нотки на екзотични цветя, теменужки,
                    черни боровинки и боров мед. Гладко, фино тяло със забележителни, зрели, сатенени танини и "гъвкави"
                    киселини. Вино с прекрасна структура, обем, хармония и потенциал.
                </description>
                <image src="wine_image2" style="width:800px;height:640px" />
            </wine>
        </winery>
    </region>
    <region id="region2">
        <name>Северозападен район</name>
        <winery id="winery2" region="region2">
            <name>Типченица</name>
            <location>с. Типченица</location>
            <year>2005</year>
            <grapes>мискет, шардоне, каберне совиньон, рубин</grapes>
            <description>Село Типченица е разположено живописно в хълмистия Северозапад, а над него, в обитавана от диви
                животни и птици местност, са лозята на едноименната изба. Още в епохата на Османската империя оттук са
                тръгвали товари с грозде към София. През социализма селото е било важен център за производство на лозов
                посадъчен материал.
            </description>
            <image src="winery_image2" style="width:800px;height:640px" />
            <wine id="wine3" winery="winery2">
                <name>Tipchenitza Winery Rubin Oak Barrel 2020</name>
                <year>2020</year>
                <grapes>Рубин</grapes>
                <description>Чист и красив рубиненочервен цвят. Атрактивен нос с карамелени нотки, зряла арония, цветя,
                    вишновка. Следно тяло, свежо и сочно, с нотки на шоколад и плодове в ликьор и кафе.Добра дължина.
                </description>
                <image src="wine_image3" style="width:800px;height:640px" />
            </wine>
            <wine id="wine4" winery="winery2">
                <name>Tipchenitza Winery Tochka Sauvignon Blanc 2019</name>
                <year>2019</year>
                <grapes>Совиньон блан</grapes>
                <description>Виното е с интензивни аромати с тонове на зелена трева, бръшлян, люляк, лимон... Подчертано
                    свежо, с повтарящи се вкусове от аромата и нотки на лимонова семка плюс лека парливост на финала.
                </description>
                <image src="wine_image4" style="width:800px;height:640px"/>
            </wine>
        </winery>
    </region>
    <region id="region3">
        <name>Дунавска равнина</name>
        <winery id="winery3" region="region3">
            <name>Винпром Свищов</name>
            <location>Свищов</location>
            <year>1948</year>
            <grapes>Каберне Совиньон, Каберне Фран, Мерло, Шардоне, Мускат, Траминер и Совиньон Блан</grapes>
            <description>Винпром Свищов е наследник на изба с над 70-годишна история. Винарната е сред
                основоположниците на вино културата в България, както и една от първите изби, стартирали
                производството на розе в страната. Годишното производство на вино възлиза на над 2 милиона литра.
            </description>
            <image src="winery_image3" style="width:800px;height:640px"/>
            <wine id="wine5" winery="winery3">
                <name>Imperium Chardonnay and Sauvignon Blanc 2015</name>
                <year>2015</year>
                <grapes>шардоне и совиньон блан</grapes>
                <description>Интензивен цвят - злато с лимонени оттенъци. Много интензивен и елегантен нос с нотки на
                    зелена маслина с бадем, сладък тропически плод, липов цвят и мокър камък. Обло, сочно и въздействащо
                    с нотки на стафида и зелени маслини едновремеменно, контрастно и елегантно до края на вкуса. Дълго и
                    благородно с послевкус на липа.
                </description>
                <image src="wine_image5" style="width:800px;height:640px"/>
            </wine>
            <wine id="wine6" winery="winery3">
                <name>Gorchivka Merlot 2016</name>
                <year>2016</year>
                <grapes>мерло</grapes>
                <description>Искрящ, рубинено червен цвят. Елегантен нос с нотки на зрели вишни и череши, фин минерален
                    тон и землисти акценти. Средно тяло, гъвкаво и живо с фин, средно продължителен финал.
                </description>
                <image src="wine_image6" style="width:800px;height:640px"/>
            </wine>
        </winery>
    </region>
    <region id="region4">
        <name>Южен черноморски район</name>
        <winery id="winery4" region="region4">
            <name>Винпром Карнобат</name>
            <location>с. Церковски</location>
            <year>1984</year>
            <grapes>Мавруд, Мерло, Кабърне, Купаж, Сирах, Рубин</grapes>
            <description>Разположен в плодородната Карнобатска котловина, десетилетия наред Винпром Карнобат създава
                вина, утвърдили се в България и света. Компанията разполага с най-големите собствени лозя у нас – над
                2000 ха. Сортовете са разнообрази: червен мискет, мускат отонел, памид, ркацители, димят, совиньон блан,
                траминер, сира, каберне совиньон, мерло, пино ноар, каберне фран и други. Винарната разполага с модерна
                производствена база, с най-големия капацитет на Балканите, с възможност за преработка на над 30 млн кг
                грозде годишно.
            </description>
            <image src="winery_image4" style="width:800px;height:640px"/>
            <wine id="wine7" winery="winery4">
                <name>Chateau Karnobat Mavrud 2017</name>
                <year>2017</year>
                <grapes>мавруд</grapes>
                <description>Цветът е бистър, наситено рубинен. Зрял нос с къпина и вишна, какао и вишневи листа. Свежо,
                    сочно и хармонично.
                </description>
                <image src="wine_image7" style="width:800px;height:640px"/>
            </wine>
            <wine id="wine8" winery="winery4">
                <name>Ethno Syrah Rubin 2017</name>
                <year>2017</year>
                <grapes>купаж</grapes>
                <description>Цветът е интензивен рубин. Атрактивен и чист плодов нос с череши и червени боровинки, със
                    средна структура и балансирана свежест. Спокоен, хармоничен финал.
                </description>
                <image src="wine_image8" style="width:800px;height:640px"/>
            </wine>
        </winery>
    </region>
    <region id="region5">
        <name>Долината на Струма</name>
        <winery id="winery5" region="region5">
            <name>Вила Мелник</name>
            <location>с. Хърсово</location>
            <year>2013</year>
            <grapes>Широка мелнишка лоза, Мелник 55, Руен, Мавруд, Тамянка, Керацуда, Сандански мискет</grapes>
            <description>Вила Мелник е малка семейна винарна. Намира се до с. Хърсово, на 6 км от гр. Мелник. Притежава
                300 дка собствени лозя, които се отглеждат с много внимание. Водещи са местните сортове – широка
                мелнишка лоза, мелник 55, руен, мавруд, тамянка, керацуда, сандански мискет. От класическите
                международни сортове са засадени каберне совиньон, мерло, сира, пино ноар, санджовезе, шардоне, вионие,
                совиньон блан.
            </description>
            <image src="winery_image5" style="width:800px;height:640px"/>
            <wine id="wine9" winery="winery5">
                <name>Villa Melnik Rare Varietes Shiroka Melnik 2018</name>
                <year>2018</year>
                <grapes>широка мелнишка лоза</grapes>
                <description>Наситен тъмно рубинен цвят. Богат нос с нотки на сушени домати, печени плодове, печено
                    месо, тиква и кестени. Средно тяло с нотки на сладки подправки и печени плодове. Елегантно и
                    благородно, сухо във финала. Отлично за пиене в момента.
                </description>
                <image src="wine_image9" style="width:800px;height:640px"/>
            </wine>
            <wine id="wine10" winery="winery5">
